Wiring up the kotlin native compiler! 🌯
- Setting konan.home
- Setting airplaneMode in konan.properties
- Attempting to compile!

Next up:

java.io.IOException: Cannot run program "/usr/bin/xcrun": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at org.jetbrains.kotlin.konan.exec.Command.getResult(ExecuteCommand.kt:98)
	at org.jetbrains.kotlin.konan.exec.Command.getOutputLines(ExecuteCommand.kt:79)
	at org.jetbrains.kotlin.konan.exec.Command.getOutputLines$default(ExecuteCommand.kt:78)
	at org.jetbrains.kotlin.konan.target.CurrentXcode.xcrun(Xcode.kt:75)

Will also, driven by failures, need to set and put stuff into KONAN_DATA_DIR.